name = "my-next-booking-site"
compatibility_date = "2024-01-01"

[build]
command = "npm run build"
output_directory = ".next"

[build.environment]
NODE_VERSION = "20"

[[redirects]]
from = "/*"
to = "/index.html"
status = 200 